export const UI = {
  APP_TITLE: "AI 번역기",
  APP_SUBTITLE: "AI 번역기",
  NAV: {
    TRANSLATE: "번역",
    SETTINGS: "설정",
    GLOSSARY: "용어집",
    HISTORY: "기록",
    THEME_TOGGLE: "다크모드 전환",
  },
  TRANSLATE_PAGE: {
    PLACEHOLDER_SOURCE: "번역할 텍스트를 입력하세요",
    PLACEHOLDER_RESULT: "번역 결과가 여기 표시됩니다",
    BUTTON_TRANSLATE: "번역하기",
    BUTTON_CANCEL: "취소",
    LABEL_SOURCE_LANG: "원본 언어",
    LABEL_TARGET_LANG: "대상 언어",
    LABEL_MODEL: "모델",
    LABEL_PROVIDER: "제공자",
    LABEL_CUSTOM_PROMPT: "번역 지시 (선택)",
    PLACEHOLDER_CUSTOM_PROMPT: "예: 비즈니스 격식체, 구어체, 전문 용어 선호",
    LABEL_GLOSSARY_TOGGLE: "용어집 사용",
    ADVANCED_OPTIONS: "고급 옵션",
    TRANSLATING: "번역 중...",
    CHAR_COUNT: (n: number) => `${n}자`,
    DETECTED_LANGUAGE: (name: string) => `감지: ${name}`,
    BUTTON_UPLOAD: "파일 불러오기",
  },
  SETTINGS_PAGE: {
    TITLE: "설정",
    SECURITY_NOTICE:
      "API 키는 브라우저 localStorage에만 저장됩니다. 서버로 전송되지 않습니다.",
    API_KEY_LABEL: "API 키",
    API_KEY_PLACEHOLDER: "API 키를 입력하세요",
    API_KEY_SET: "설정됨",
    API_KEY_EMPTY: "미설정",
    MODEL_LABEL: "모델",
    BUTTON_SAVE: "저장",
    BUTTON_TEST: "테스트",
    BUTTON_DELETE: "삭제",
    ADD_PROVIDER_TITLE: "새 provider 추가",
    PROVIDER_NAME: "이름",
    PROVIDER_BASE_URL: "Base URL",
    PROVIDER_MODELS: "모델 (쉼표로 구분)",
    PROVIDER_DEFAULT_MODEL: "기본 모델",
    BUTTON_ADD: "추가",
    NO_PROVIDERS: "설정된 provider가 없습니다.",
  },
  GLOSSARY_PAGE: {
    TITLE: "용어집",
    TOGGLE_LABEL: "용어집 사용",
    EMPTY_MESSAGE: "아직 용어가 없습니다. 번역에 반영하려면 용어를 추가하세요.",
    COLUMN_SOURCE: "원본",
    COLUMN_TARGET: "번역",
    COLUMN_NOTE: "메모",
    ENTRY_SOURCE_PLACEHOLDER: "원본 용어",
    ENTRY_TARGET_PLACEHOLDER: "번역 용어",
    ENTRY_NOTE_PLACEHOLDER: "메모 (선택)",
    BUTTON_ADD: "추가",
    BUTTON_EDIT: "수정",
    BUTTON_DELETE: "삭제",
    ENTRY_COUNT: (n: number) => `총 ${n}개 용어`,
  },
  HISTORY_PAGE: {
    TITLE: "번역 기록",
    EMPTY_MESSAGE: "번역 기록이 없습니다.",
    BUTTON_CLEAR_ALL: "전체 삭제",
    BUTTON_DETAIL: "자세히",
    BUTTON_DELETE: "삭제",
    CONFIRM_CLEAR: "모든 기록을 삭제하시겠습니까?",
    LIMIT_NOTICE: "100개를 초과하면 가장 오래된 항목이 자동 삭제됩니다.",
    CREATED_AT_FORMATTER: (date: Date) =>
      date.toLocaleString("ko-KR", {
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
        hour: "2-digit",
        minute: "2-digit",
      }),
  },
  ERRORS: {
    NO_API_KEY: "API 키를 설정에서 입력하세요.",
    NO_ACTIVE_PROVIDER: "활성 provider가 없습니다. 설정에서 선택하세요.",
    EMPTY_SOURCE: "번역할 텍스트를 입력하세요.",
    INVALID_REQUEST: "요청 형식이 잘못되었습니다.",
    INVALID_API_KEY: "API 키를 확인하세요. 설정에서 다시 입력해 주세요.",
    RATE_LIMITED: "요청이 너무 많습니다. 잠시 후 다시 시도해 주세요.",
    PROVIDER_ERROR: "번역 서비스에 일시적인 문제가 있습니다.",
    STREAM_INTERRUPTED: "번역이 중단되었습니다. 네트워크 연결을 확인하세요.",
    NETWORK_ERROR: "네트워크 오류가 발생했습니다.",
    STORAGE_FULL: "저장 공간이 가득 찼습니다. 오래된 기록을 삭제해 주세요.",
    INVALID_FILE_TYPE: ".txt 파일만 업로드할 수 있습니다.",
    UNKNOWN: "알 수 없는 오류가 발생했습니다.",
  },
} as const;
